### ISSUE TITLE
I reached out to whats app support, they said it was intentional.

### ISSUE THREAD

**Issue by elfakyn** [ldicarlo/android-channels-problem#1]
Great research! I was looking into it separately and I came to the same conclusion, it keeps creating notification channels. Glad to see solid confirmation.

According to support this is intentional:

> Hi,
>
> On Android 10, WhatsApp added special rules for group notifications and message notifications:
>
> These notifications are always on by default. If you turn them off, the notifications will turn back on when you receive a message.
> Silent importance is disabled. If you set notifications to Silent importance, the notifications will automatically change to Alerting importance when you receive a message.
> You can adjust your WhatsApp notifications in device Settings > Apps & Notifications > WhatsApp > App notifications. If you want to set the behavior to *Other* importance, you can set the notification sound to None. For all other pre-populated notifications, we don't recommend modifying importance.
>
> This is an intended functionality of the app. We apologize for any confusion.
>
> Regards,
> <REDACTED>
> WhatsApp Support Team

This is horrendous design and it's baffling that they went out of their way to have this behavior. Bypassing all of Google's protections around notification abuse can't be easy.

I don't know if you want to add this additional information in the repo or whatever.

**Comment by ldicarlo** [comment]
Thank you !
I added it to the repo.

**Comment by elfakyn** [comment]
Cool!
